pipeline {
 agent any

 stages {
   stage('Checkout'){
   }

   stage('Build'){
   }

   stage('Sonar'){
   }

   stage('Artifact Upload'){
   }

   stage('Docker Build'){
   }

   stage('Image Push'){
   }

   stage('Deploy'){
   }
 }
}